# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Research Software Engineering: Bridging Knowledge Gaps"
# email: bernholdtde@ornl.gov # We really don't have a single point of email contact for the seminar as a whole
description: >- # this means to ignore newlines until "baseurl:"
  This website collects outputs and resources to help bridge between
  the software engineering research (SER) and research software engineering (RSE)
  communities.  This effort originated in the April 2024 Dagstuhl Seminar 
  "[Research Software Engineering: Bridging Knowledge Gaps](https://www.dagstuhl.de/24161)" 
  (number 24161).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ser-rse-bridge.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "air"

subtitle: Dagstuhl Seminar 24161, April 2024
name: The participants in Dagstuhl seminar 24161

teaser: /assets/images/LZI-Logo.jpg
logo: /assets/images/LZI-Logo.jpg
og_image: /assets/images/LZI-Logo.jpg

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#  - README.md

repository: ser-rse-bridge/ser-rse-bridge.github.io

# This is needed to generate output for future events
future: true

footer:
  links:
    - label: "Dagstuhl Seminar 24161"
      icon: fas fa-link
      url: https://www.dagstuhl.de/24161
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ser-rse-bridge/ser-rse-bridge.github.io"
#    - label: "Licensed CC-BY unless otherwise indicated"
#      icon: "fab fa-creative-commons-by"
#      url: "https://creativecommons.org/licenses/by/4.0/"